### PR TITLE
[WIP] add tutorial

### PR DESCRIPTION
**Pull request by monaqa**
I translated the part of the article 「[Deno で Vim/Neovim のプラグインを書く (denops.vim)](https://zenn.dev/lambdalisue/articles/b4a31fba0b1ce95104c9)」 corresponding to the chapter 「[開発チュートリアル](https://zenn.dev/lambdalisue/articles/b4a31fba0b1ce95104c9#%E9%96%8B%E7%99%BA%E3%83%81%E3%83%A5%E3%83%BC%E3%83%88%E3%83%AA%E3%82%A2%E3%83%AB) (= Development Tutorial)」.

- [x] 2.1. Preparation
- [x] 2.2. Create directory
- [x] 2.3. Create skeleton
- [x] 2.4. Add application interfaces
- [x] 2.5. Call Vim/Neovim features
- [ ] 2.6. Create authentic plugin

### CODE REVIEW

**Comment by kkiyama117** [comment]
I feel this translation is literally a great job, but I think it seems [this sentence](https://github.com/vim-denops/denops-documentation/blob/dee157adeb296e1bb238dde3501500032b2b211b/src/tutorial/add_application_interfaces.md#L24) may be 
` ..., you can only register functions whose arguments are all unknown type and ....` or ` ..., you can only register functions all arguments has unknown type ..., `

**Comment by monaqa** [comment]
@kkiyama117 Thank you for your review.

> whose arguments are all of unknown type

I think "A is of type (type name)" is a commonly used expression.
"unknown" in this sentence means a specific type in TypeScript, so this translation is certainly not appropriate.
So I feel it would be better to change the phrase to "whose arguments are all of type `unknown`."

Or, based on your suggestion, the following translation could be considered.

- you can only register functions where all arguments has type `unknown`

How do you feel about this?

**Comment by lambdalisue** [comment]
Duplicate with #5 (which seems already completed). It would be nice we could merge this and #5 thus I've added @monaqa to the reviewer of #5 🙇

**Comment by lambdalisue** [comment]
Closed due to #5

**Pull request closed without merging**
